import { ClaimBanner, PublicHeader, PublicLead } from "../public-league";

export const metadata = { title: "League Guide | Action Line-Up", description: "Seguin 8Ball League night guide." };

const topics = [["Rack and break", "Rack alternating solids and stripes with the 8-ball centered. The cue ball starts completely behind the head string, must hit the head ball first, and at least four balls must reach a rail for a legal break."], ["Call every shot", "Call the pocket, object-ball rails, and carom contacts. The friendly rail into a corner and rails inside the pocket are exceptions."], ["No safety play", "A real attempt to pocket an object ball is required. Intentional fouls used as safeties can be reviewed by the Board and may cost a game or league eligibility."], ["Scratches and fouls", "After a scratch, the incoming player places the cue ball completely behind the head string. Fouling while pocketing the 8-ball is loss of game."], ["Rosters and fees", "Teams may have up to eight players. Lineups lock after week 8 without Board approval. Player fees are due by week 4, and teams pay a $50 weekly fee, including bye weeks to receive the win."], ["Score sheets and rulings", "Complete, legible score sheets document wins, losses, break-and-runs, table runs, and 8s on the break. For an unusual situation, stop before the next shot; the Board’s ruling controls."]];

export default function RulesPage() {
  return <main className="public-page"><PublicHeader current="rules" /><div className="public-wrap"><PublicLead icon="rules" title="Seguin 8 Ball League rules" text="Official bylaws and rules loaded September 1, 2026" /><section className="rules-notice"><strong>Official Seguin rules are active</strong><p>This guide summarizes the supplied Seguin 8 Ball League Bylaws and Rules. Rule Desk uses those rules for common questions. For any situation not covered here, pause before the next shot and follow the Board’s official ruling.</p></section><section className="rules-list">{topics.map(([title, text], index) => <article key={title}><b>{index + 1}</b><div><h2>{title}</h2><p>{text}</p></div></article>)}</section><ClaimBanner /></div></main>;
}
